<?php

/**
 * E-Mail-Templates Einstellungen
 * 
 * @package issue_tracker
 */

$package = rex_addon::get('issue_tracker');

// Nur Admins dürfen Einstellungen ändern
if (!rex::getUser()->isAdmin()) {
    echo rex_view::error($package->i18n('issue_tracker_no_permission'));
    return;
}

// Templates speichern
if (rex_post('save_templates', 'int', 0) === 1) {
    $languages = ['de', 'en'];
    $templates = ['new_issue', 'new_comment', 'status_change', 'assignment'];
    
    foreach ($languages as $lang) {
        foreach ($templates as $template) {
            $key = 'email_template_' . $template . '_' . $lang;
            $value = rex_post($key, 'string', '');
            
            rex_sql::factory()
                ->setTable(rex::getTable('issue_tracker_settings'))
                ->setValue('setting_key', $key)
                ->setValue('setting_value', $value)
                ->insertOrUpdate();
        }
    }
    
    echo rex_view::success($package->i18n('issue_tracker_settings_saved'));
}

// Defaults setzen, wenn noch nicht vorhanden
$defaultTemplates = [
    'new_issue_de' => "Hallo {{recipient_name}},\n\nes wurde ein neues Issue erstellt:\n\nTitel: {{issue_title}}\nKategorie: {{issue_category}}\nPriorität: {{issue_priority}}\nErstellt von: {{creator_name}}\n\nBeschreibung:\n{{issue_description}}\n\nZum Issue: {{issue_url}}\n(Dieser Link ist nur einmal verwendbar und 30 Tage gültig)\n\n---\nDiese E-Mail wurde automatisch vom REDAXO Issue Tracker generiert.",
    
    'new_issue_en' => "Hello {{recipient_name}},\n\na new issue was created:\n\nTitle: {{issue_title}}\nCategory: {{issue_category}}\nPriority: {{issue_priority}}\nCreated by: {{creator_name}}\n\nDescription:\n{{issue_description}}\n\nView issue: {{issue_url}}\n(This link is valid for one-time use and 30 days)\n\n---\nThis email was automatically generated by REDAXO Issue Tracker.",
    
    'new_comment_de' => "Hallo {{recipient_name}},\n\nes wurde ein neuer Kommentar zu Issue #{{issue_id}} hinzugefügt:\n\nIssue: {{issue_title}}\nKommentar von: {{creator_name}}\n\n{{comment_text}}\n\nZum Issue: {{issue_url}}\n(Dieser Link ist nur einmal verwendbar und 30 Tage gültig)\n\n---\nDiese E-Mail wurde automatisch vom REDAXO Issue Tracker generiert.",
    
    'new_comment_en' => "Hello {{recipient_name}},\n\na new comment was added to issue #{{issue_id}}:\n\nIssue: {{issue_title}}\nComment by: {{creator_name}}\n\n{{comment_text}}\n\nView issue: {{issue_url}}\n(This link is valid for one-time use and 30 days)\n\n---\nThis email was automatically generated by REDAXO Issue Tracker.",
    
    'status_change_de' => "Hallo {{recipient_name}},\n\nder Status von Issue #{{issue_id}} wurde geändert:\n\nIssue: {{issue_title}}\nAlter Status: {{old_status}}\nNeuer Status: {{new_status}}\n\nZum Issue: {{issue_url}}\n(Dieser Link ist nur einmal verwendbar und 30 Tage gültig)\n\n---\nDiese E-Mail wurde automatisch vom REDAXO Issue Tracker generiert.",
    
    'status_change_en' => "Hello {{recipient_name}},\n\nthe status of issue #{{issue_id}} was changed:\n\nIssue: {{issue_title}}\nOld status: {{old_status}}\nNew status: {{new_status}}\n\nView issue: {{issue_url}}\n(This link is valid for one-time use and 30 days)\n\n---\nThis email was automatically generated by REDAXO Issue Tracker.",
    
    'assignment_de' => "Hallo {{recipient_name}},\n\nIhnen wurde ein Issue zugewiesen:\n\nIssue #{{issue_id}}: {{issue_title}}\nKategorie: {{issue_category}}\nPriorität: {{issue_priority}}\n\nBeschreibung:\n{{issue_description}}\n\nZum Issue: {{issue_url}}\n(Dieser Link ist nur einmal verwendbar und 30 Tage gültig)\n\n---\nDiese E-Mail wurde automatisch vom REDAXO Issue Tracker generiert.",
    
    'assignment_en' => "Hello {{recipient_name}},\n\nan issue was assigned to you:\n\nIssue #{{issue_id}}: {{issue_title}}\nCategory: {{issue_category}}\nPriority: {{issue_priority}}\n\nDescription:\n{{issue_description}}\n\nView issue: {{issue_url}}\n(This link is valid for one-time use and 30 days)\n\n---\nThis email was automatically generated by REDAXO Issue Tracker."
];

// Templates laden
$sql = rex_sql::factory();
$templates = [];

foreach ($defaultTemplates as $key => $defaultValue) {
    $sql->setQuery('SELECT setting_value FROM ' . rex::getTable('issue_tracker_settings') . ' WHERE setting_key = ?', ['email_template_' . $key]);
    $templates[$key] = $sql->getRows() > 0 ? $sql->getValue('setting_value') : $defaultValue;
}

?>

<form method="post">
    <input type="hidden" name="save_templates" value="1" />
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?= $package->i18n('issue_tracker_email_templates') ?></h3>
        </div>
        <div class="panel-body">
            <p class="help-block">
                <?= $package->i18n('issue_tracker_email_templates_help') ?><br>
                <strong><?= $package->i18n('issue_tracker_available_placeholders') ?>:</strong>
                <code>{{recipient_name}}</code>, <code>{{issue_id}}</code>, <code>{{issue_title}}</code>,
                <code>{{issue_category}}</code>, <code>{{issue_priority}}</code>, <code>{{issue_description}}</code>,
                <code>{{creator_name}}</code>, <code>{{comment_text}}</code>, <code>{{old_status}}</code>,
                <code>{{new_status}}</code>, <code>{{issue_url}}</code>
            </p>
            
            <ul class="nav nav-tabs" role="tablist">
                <li class="active"><a href="#tab-de" role="tab" data-toggle="tab">Deutsch</a></li>
                <li><a href="#tab-en" role="tab" data-toggle="tab">English</a></li>
            </ul>
            
            <div class="tab-content" style="padding-top: 20px;">
                <!-- Deutsche Templates -->
                <div id="tab-de" class="tab-pane active">
                    <h4><?= $package->i18n('issue_tracker_template_new_issue') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_new_issue_de" class="form-control" rows="10"><?= htmlspecialchars($templates['new_issue_de']) ?></textarea>
                    </div>
                    
                    <h4><?= $package->i18n('issue_tracker_template_new_comment') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_new_comment_de" class="form-control" rows="10"><?= htmlspecialchars($templates['new_comment_de']) ?></textarea>
                    </div>
                    
                    <h4><?= $package->i18n('issue_tracker_template_status_change') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_status_change_de" class="form-control" rows="10"><?= htmlspecialchars($templates['status_change_de']) ?></textarea>
                    </div>
                    
                    <h4><?= $package->i18n('issue_tracker_template_assignment') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_assignment_de" class="form-control" rows="10"><?= htmlspecialchars($templates['assignment_de']) ?></textarea>
                    </div>
                </div>
                
                <!-- Englische Templates -->
                <div id="tab-en" class="tab-pane">
                    <h4><?= $package->i18n('issue_tracker_template_new_issue') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_new_issue_en" class="form-control" rows="10"><?= htmlspecialchars($templates['new_issue_en']) ?></textarea>
                    </div>
                    
                    <h4><?= $package->i18n('issue_tracker_template_new_comment') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_new_comment_en" class="form-control" rows="10"><?= htmlspecialchars($templates['new_comment_en']) ?></textarea>
                    </div>
                    
                    <h4><?= $package->i18n('issue_tracker_template_status_change') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_status_change_en" class="form-control" rows="10"><?= htmlspecialchars($templates['status_change_en']) ?></textarea>
                    </div>
                    
                    <h4><?= $package->i18n('issue_tracker_template_assignment') ?></h4>
                    <div class="form-group">
                        <textarea name="email_template_assignment_en" class="form-control" rows="10"><?= htmlspecialchars($templates['assignment_en']) ?></textarea>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">
                <i class="rex-icon fa-save"></i> <?= $package->i18n('issue_tracker_save') ?>
            </button>
        </div>
    </div>
</form>
